name: listasmart
description: "App de listas de compras inteligente"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Backend
  supabase_flutter: ^2.5.6

  # UI
  cupertino_icons: ^1.0.6

  # PDF Generation
  pdf: ^3.10.8
  path_provider: ^2.1.3

  # Sharing
  share_plus: ^9.0.0

  # Utilities
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.12
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true